### ISSUE TITLE
Bug: "Return to top" link collides with body content at less than desktop viewports on news items

### ISSUE THREAD

**Issue by jonadecker** [GSA-TTS/10x-website#131]
### Who discovered this?

jona.decker@gsa.gov

### What happened?

I resized the viewport to fit two browser windows on screen. The "Return to top" link appears on top of body text (but is still clickable.)
![Screenshot 2024-03-26 at 2 16 42 PM](https://github.com/GSA-TTS/10x-website/assets/1735772/709af15d-1090-4ba5-9718-295932766b25)
![Screenshot 2024-03-26 at 2 16 51 PM](https://github.com/GSA-TTS/10x-website/assets/1735772/9bab6506-292d-4261-8347-b0d209ce7b4e)
![Screenshot 2024-03-26 at 2 17 10 PM](https://github.com/GSA-TTS/10x-website/assets/1735772/cc1d4e0f-44bf-43f6-9e63-81b50c2b2d67)

### What pages did this appear on?

This appears on pages with left sidenav and long body copy, e.g.., the News posts. It does appear on About sub-pages that have the same structure but it's less apparent because these pages have less copy (currently).

### Detail the steps for someone to reproduce

1. Browse to a long news post like [2024 Selected Investments](https://10x.gsa.gov/news/2024-selected-investments/)
2. Resize viewport until left nav column falls below body
3. Scroll

### What browsers are you seeing the problem on?

Chrome

**Comment by natashapl** [comment]
Hi @jonadecker . I just pushed a fix for this issue. Please review:

https://federalist-37831b52-7633-429a-9a79-14298034dd54.sites.pages.cloud.gov/preview/gsa-tts/10x-website/fix-return-to-top-link/
