### ISSUE TITLE
Improve Open Graph support for News / Impact Reports / Repo

### ISSUE THREAD

**Issue by maomeara63** [GSA-TTS/10x-website#159]
- [x] Identify what pages or sections would benefit from custom open graph images. Current thinking is News items and Impact Reports, plus Repo itself (manual addition within Repo Admin settings)
- [x] Designate an area where custom open graph image assets should be uploaded to customize  social media preview.
- [x] Create front matter support to allow pointing to custom open graph images and (potentially) other custom open graph tags.

Notes: 
- Open Graph images should be at least 640×320px (1280×640px for best display).

**Comment by jonadecker** [comment]
![Image](https://github.com/GSA-TTS/10x-website/assets/1735772/6853e9cf-30da-4d02-8e82-aa26ad7de528)
