### ISSUE TITLE
Tell us Once post -- Target date: Sept 3, 2024

### ISSUE THREAD

**Issue by maomeara63** [GSA-TTS/10x-website#205]

**Comment by maomeara63** [comment]
[Copy ](https://docs.google.com/document/d/10vlz48GDWugB7XpB2XxZfO_QJQQlJobWtJcLBq7rYZ8/edit)

**Comment by maomeara63** [comment]
[Revised News Landing Page copy](https://docs.google.com/document/d/10vlz48GDWugB7XpB2XxZfO_QJQQlJobWtJcLBq7rYZ8/edit?usp=sharing)

10x is evolving to include Concept Areas, which allows us to focus on big problems requiring sustained attention.

**Comment by jonadecker** [comment]
@maomeara63 may I suggest concentrated attention? Sustained seems more passive than intended.

**Comment by maomeara63** [comment]
@jonadecker Perfect. Thank you.
