### ISSUE TITLE
Copy change: FY25 idea evaluation

### ISSUE THREAD

**Issue by maomeara63** [GSA-TTS/10x-website#207]
**User story**
As an Idea Submitter, I want it to be clear that while I can submit an idea at any time, 10x will not be evaluating new ideas in Q1 2025 (so I may not hear whether my idea has been selected for 12+ months).

**Definition of Done**

- [x] Copy appears in relevant places (top of Submit an idea; further down page near Submit an Idea button)

**Tasks**

- [x] Write copy
- [x] Approve copy
- [x] Publish copy

Also consider providing message on Qualtrics form or reply email.

**Comment by maomeara63** [comment]
@marina-defrates Can you identify the typo that needs to be fixed?

**Comment by maomeara63** [comment]
@marina-defrates Please review (and approve, if you are so inclined), the copy explaining that we aren't evaluating ideas this year.

[Copy](https://docs.google.com/document/d/1IrklPCDVaT5dG0O0koyxZpPZdnuDZFL2AkEIykZEeJY/edit?usp=sharing)

**Comment by maomeara63** [comment]
@marina-defrates The "Submit an idea" copy change will appear in this block:


![Image](https://github.com/user-attachments/assets/f6d0e9e3-0e38-4efe-840d-75382008a3fd)

**Comment by marina-defrates** [comment]
LGTM
