### ISSUE TITLE
Bug: Should all headings have focus?

### ISSUE THREAD

**Issue by maomeara63** [GSA-TTS/10x-website#211]
### Who discovered this?

Meghan

### What happened?

Noticed on [Announcing 10x's exciting new investments ](https://10x.gsa.gov/news/2024-selected-investments/) that H2s have focus but not H3s. Should they all have focus? Or just those in the Impact Reports where they are needed for navigation?

### What pages did this appear on?

[Announcing 10x's exciting new investments ](https://10x.gsa.gov/news/2024-selected-investments/) and others with subheads.

### Detail the steps for someone to reproduce

1. Go to the page.
2. Click on an H2 and see the focus box.
3. Click on an H3 and note that there is no focus box.

### What browsers are you seeing the problem on?

Chrome

**Comment by natashapl** [comment]
Hi. I raised this question during the "Intro to Manual Accessibility Training," and both Robert and Jason confirmed that headers only receive focus if they contain an anchor (i.e., are a link) or are associated with in-page navigation.
